### ISSUE TITLE
Infix operators have reduce/reduce conflicts

### ISSUE THREAD

**Issue by Ekdohibs** [Ekdohibs/camlboot#11]
# Steps to reproduce
Try the [infix](https://github.com/Ekdohibs/camlboot/tree/infix) branch, and run `compile.scm`. You will get a warning `%% Reduce/Reduce conflict (reduce 84, reduce 48) on 'RPAREN' in state 96`. I don't know the source of the conflict.

**Comment by gasche** [comment]
My debugging technique would be to revert all changes from `LIDENT` to `lident_ext`, and then reintroduce them one by one to see where the conflict appears.

Note: I think it would probably be fine to also allow parenthesized operators in field names, to remove the distinction between `LIDENT` and `lident_ext` completely, and get a simpler patch. But you have already implemented the more-careful approach, so we can keep that.

**Comment by Ekdohibs** [comment]
I tried to do that without much success... It seems like the conflict arises as soon as the rule `longident_lident -> lident_ext` exists (with the rule `longident_lident -> longident_uident DOT lident_ext` being fine as is).
Besides, I tried to replace the rule for the construction of a record to only allow `longident_field` instead of `longident_lident`, and I was greeted by two other conflicts, which seem to exist only if both the rules for `'ERecord` and `'ERecordwith` are present: if either of them is disabled, both conflicts disappear.
I must say I am a bit lost here, and I don't have enough intuition to know where the conflicts come from. It is possible that they originate from the parser generator handling only LALR(1) and not LR(1), but I'd still be surprised by that. Do you have any idea about this?

**Comment by gasche** [comment]
I'm happy to try looking at it, but later. (In case you are curious: the PhD defense of François Thiré just started, I can send you the URL in case you want to know about translating proofs between pure-type-systems-with-extensions systems.)

**Comment by Ekdohibs** [comment]
I have found the problem: `( * )` would have been allowed in `type_ignore` and related as both a `longident_lident` and a succession of parentheses and allowed symbols in this context.
However, it doesn't fix the problem with records, so I'm leaving the issue open for now.

**Comment by Ekdohibs** [comment]
Found the other conflict. It happened because something like `{ a = 7 with ... }` was accepted by the grammar.
