### ISSUE TITLE
document the time required to bootstrap

### ISSUE THREAD

**Issue by gasche** [Ekdohibs/camlboot#51]
Before even considering reproducing a debootstrap experiment, I would want to know how long it's going to take, or at least how long it took for people who did it in the past. I complain about other projects not providing this information, but we don't either. I'm opening this issue to track this: we should include complete build time on someone's machine directly in the README.

**Comment by Ekdohibs** [comment]
There is a comment at the end of the README concerning the build time. Is this what you expect, or did you expect something more detailed?

**Comment by gasche** [comment]
Ah, yes! I probably was looking at the outdated README of my development version. This can be closed, thanks.

P.S.: the README says:

> After cloning, you first need to clone the `ocaml/` submodule, with `git submodule init && git submodule update --recursive`

I believe it should be `ocaml-src/`?
